#!/usr/bin/env bash
# Function to display processes in a hierarchical format

printf "%-8s %-5s %-8s %s\n" "USER" "PID" "START" "COMMAND"

# Use ps with selected columns and format them
ps -eo user=,pid=,lstart=,cmd= --no-headers | while read -r user pid day month date time year cmd; do
    start_time="$time"
    printf "%-8s %-5s %-8s %s\n" "$user" "$pid" "$start_time" "$cmd"
done
