#!/usr/bin/env bash
# without using ps command

for pid in /proc/[0-9]*; do
    exe_path=$(readlink "$pid/exe" 2>/dev/null)
    if [[ "$exe_path" == *bash* ]]; then
        echo "$(basename "$pid") $exe_path"
    fi
done
