#!/usr/bin/env bash
# Send SIGTERM to 7-highlander processes and output OK

trap 'echo "I am invincible!!!"' SIGTERM
trep 'echo "OK"' SIGKILL

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
