#!/usr/bin/env bash
# Kill the 7-highlander process using SIGKILL (signal 9)

pids=$(pgrep -f 7-highlander)

# Send SIGKILL to each PID
if [ -n "$pids" ]; then
    for pid in $pids; do
        kill -9 "$pid"
    done
fi
